version: "3.9"
services:
  getconnected:
    build:
      context: getconnected/
  balance:
    build:
      context: balance/
    environment:
      WALLET_ADDRESS: ${WALLET_ADDRESS}
  airdrop:
    build:
      context: airdrop/
    environment:
      WALLET_ADDRESS: ${WALLET_ADDRESS}
  account:
    build:
      context: account/
    environment:
      WALLET_ADDRESS: ${WALLET_ADDRESS}
  mintaccount:
    build:
      context: mintaccount/
    environment:
      PRIVATE_KEY: ${PRIVATE_KEY}
  tokenaccount:
    build:
      context: tokenaccount/
    environment:
      MINT_KEY: ${MINT_ACCOUNT}
      PRIVATE_KEY: ${PRIVATE_KEY}
  mintnft:
    build:
      context: mintnft/
    environment:
      PRIVATE_KEY: ${PRIVATE_KEY}
